services:
  node:
    image: hive:latest
    restart: unless-stopped
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
